function bang(liczba)
{
	var a1 = "<div style=\"text-align:center;padding:12px;height:320px;width:750px;margin:auto;margin-bottom:25px;border-radius:10px;background-color: rgba(200,200,200,0.75);\" class=\"text\"><span class=\"a\">Rower XC(Cross Country)</span></br></br>Rower ten będzie znakomity dla pasjonatów jazdy w lekkim i umiarkowanie trudnym terenie, a także po górach. Również dla osób jeżdżących zawodowo.</br></br>Na rynku znajdziemy 3 rozmiary kół: klasyczny – 26 cali; 27,5 cala oraz 29 cali. Większe koło przyczynia się do gorszej zwrotności roweru, a także podnosi jego wagę. Jednak gdy zjedziemy z asfaltu w teren, rower z większymi kołami będzie lepiej podjeżdżał, pokonywał przeszkody (dziury, korzenie, kamienie itp), a także będzie stabilniejszy na zjazdach. Dobierając wielkość koła, powinniśmy kierować się głównie naszymi preferencjami. Wzrost jest istotny jedynie w przypadku bardzo niskich lub bardzo wysokich rowerzystów.</br></br>Za amortyzację odpowiada w tej grupie najczęściej amortyzator o skoku 100 mm. Jeżeli chcesz się ścigać na rowerze, to dobrze by było, aby znalazł się w nim amortyzator klasy co najmniej Rock Shox Reba.</br></br>W przypadku tanich rowerów powinniśmy zdać sobie sprawę, że proste modele widelców bardzo szybko łapią luzy. Jeżeli w rowerze będą jeszcze hamulce tarczowe, to przyspieszy ten proces jeszcze bardziej.</div>";
	
	var a2 = "<div style=\"text-align:center;padding:12px;height:280px;width:750px;margin:auto;margin-bottom:25px;border-radius:10px;background-color: rgba(200,200,200,0.75);\" class=\"text\"><span class=\"a\">Rower Trailowy</span></br></br>Rower tego typu, to złoty środek pomiędzy rowerem enduro, a rowerem XC. Został on stworzony, aby dawać jak największą frajdę z jazdy. Jego konstrukcja pozwala łatwo pokonywać zjazdy, podjazdy, a także długie górskie trasy rowerowe.</br></br>Rower trailowy może występować jako rower z pełnym zawieszeniem albo jako hardtail. Co wyróżnia ten rower, to nie zawieszenie, a geometria. Jest ona zaprojektowana tak, aby zapewnić rowerzyście jak największą stabilność, a także zwrotność. Nowoczesne rowery trail mają mniej soku niż rowery enduro – ok. 130-150 mm.</br></br>W niektórych rowerach trailowych producenci zastosowali nowy typ kół i opon – plus. Są to bardzo szerokie koła, które zapewniają jeszcze większą przyczepność podczas jazdy.</br></br>Na rower tego typu jedynie z amortyzowanym widelcem, trzeba wydać od 4000 zł do 10.000 zł. Natomiast jeżeli chciałbyś bardziej komfortowy rower z pełnym zawieszeniem, musisz wydać od 7000 zł do 17.000 zł.</div>";
		
	var a3 = "<div style=\"text-align:center;padding:12px;height:280px;width:750px;margin:auto;margin-bottom:25px;border-radius:10px;background-color: rgba(200,200,200,0.75);\" class=\"text\"><span class=\"a\">Rower Enduro</span></br></br>Rowery Enduro są tak zaprojektowane, aby pokonywać trudne strome zjazdy, które są usłane masą dziur, korzeni, kamieni i innych przeszkód. Od roweru downhill odróżnia go to, że jest w stanie z powrotem wjechać na stromy szczyt.</br></br>Rowery enduro mają zwykle mniejszy skok niż rowery downhill, ale też posiadają pełne zawieszenie. Rowery tego typu są wyposażone w ok. 160 – 170 mm skoku widelca, a także dampera.</br></br>Niektóre rowery enduro wyposażone są w zmienną geometrię, sterowaną za pomocą jednego przycisku. Dzięki temu możemy jednym kliknięciem przystosować rower do zjazdu lub podjazdu. W taki system jest wyposażony np. rower Canyon Strive.</br></br>Rowery enduro są dla osób, które lubią pokonywać trudne technicznie zjazdy, a zarazem zdobywać szczyty. Ceny tego typu rowerów zaczynają się od ok. 7000 zł, a dobry rower enduro można kupić za ok. 13.000 zł. Rower z najwyższej półki, z karbonową ramą, kosztuje ok. 20.000 zł.</div>";	
	
	var a4 = "<div style=\"text-align:center;padding:12px;height:240px;width:750px;margin:auto;margin-bottom:25px;border-radius:10px;background-color: rgba(200,200,200,0.75);\" class=\"text\"><span class=\"a\">Fat Bike</span></br></br>Fatbike’i odróżniają się od innych rowerów tym, że są wyposażone w bardzo szerokie opony (od 4 cali w górę). Pozwalają one jeździć na niskim ciśnieniu, dzięki czemu rower posiada znakomitą przyczepność.  Taki rower znakomicie sprawdza się w czasie zimy, a także w trakcie jazdy po piasku. Fat Bike występują z amortyzowanym widelcem lub w wersjach całkowicie sztywnych.</br></br>Według mnie jest to rower dla osób u których sezon rowerowy trwa nawet zimą, a rowery z kołami „Plus” im nie wystarczają.</br></br>Fat Bike można kupić już za 1000 zł, ale nie można spodziewać się od rowerów za tą cenę dobrej jakości. Aby kupić dobrego Fat Bike trzeba wydać ok. 4000 zł, jednak jeśli potrzebujemy niesamowitą maszynę, wyposażoną w najnowsze technologie i podzespoły, to musimy przygotować nasz portfel na wydatek rzędu ok. 10.000 zł.</div>";
		
	var a5 = "<div style=\"text-align:center;padding:12px;height:280px;width:750px;margin:auto;margin-bottom:25px;border-radius:10px;background-color: rgba(200,200,200,0.75);\" class=\"text\"><span class=\"a\">Rower Downhillowy</span></br></br>Rower tego typu jest głównie przeznaczony dla osób kochających adrenalinę, szybkość i zjazdy na których zawsze coś się dzieje.</br></br>Takie rowery zazwyczaj są wyposażone w widelec o skoku ok. 200 mm. W tych rowerach dampery często posiadają sprężynę zwojową, która jest bardzo wytrzymała, a także jest zoptymalizowana pod kątem jak największej przyczepności, a nie pedałowania, przez co damper pochłania siłę pedałowania. Natomiast przedni widelec jest już wyposażony w sprężynę powietrzną.</br></br>Taki rower powinieneś kupić, gdy lubisz szybko jeździć na bardzo trudnych zjazdach, a także latać w przestworza. Musisz pamiętać, że na tym rowerze bardzo ciężko Ci będzie wjechać pod strome podjazdy.</br></br>Ceny nowych rowerów downhillowych zaczynają się od ok. 7500 zł do nawet 43.000 zł.</div>";
		
	if(liczba==1) document.getElementById("info-arcus").innerHTML = a1;
	else if(liczba==2)document.getElementById("info-arcus").innerHTML = a2;
	else if(liczba==3)document.getElementById("info-arcus").innerHTML = a3;
	else if(liczba==4)document.getElementById("info-arcus").innerHTML = a4;
	else if (liczba==5)document.getElementById("info-arcus").innerHTML = a5;
}
